name: Probar DevSecOps Antivirus Localmente

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-antivirus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Ejecutar DevSecOps Antivirus Action
        # Llama a la action definida en el directorio raíz de este mismo repositorio
        uses: ./
